In [2]:
import numpy as np
import tensorflow as tf

# Linear Regression (once again):

<img src="images/LR.png">


Recall that Linear Regression with Gradient Descent involves the following steps:


***
__1. Collect predictions *(Forward Pass)*__ :
\begin{align}
\ \tilde{y_i} &= mx_i + b \\
\end{align}
***

***
__2. Compute Mean Squared Error / Loss:__
\begin{align}
\ L & = \frac{1}{N} \sum_{k=1}^N (y_k - \tilde{y_k})^2 \\
\end{align}
***

***
__3. Compute Derivatives _(Backward Pass)_ :__
\begin{align}
\ \frac{\partial L}{\partial m} &= -\frac{2}{N} \sum_{k=1}^N x_k(y_k - \tilde{y_k})\\
\end{align}
\begin{align}
\ \frac{\partial L}{\partial b} &= -\frac{2}{N} \sum_{k=1}^N (y_k - \tilde{y_k})\\
\end{align}
***

***
__4. Update Parameters:__
\begin{align}
\ m &= m - \alpha \frac{dL}{dm} \\
\ b &= b - \alpha \frac{dL}{db} \\
\end{align}
***

        

__Represented as a Computational Graph:__

<img src="images/comp-graph.png" alt="drawing" style="width:100px;"/>


<font color="green"> __This reveals the essential Buidling Blocks of a Deep Learning API__ </font>


1. __Tensors__
2. __Variables__
3. __Computational Graph__
4. __Automatic differentiation__


# 1. Tensors

Similar to numpy arrays, Tensors are multi-dimensioanl arrays of a uniform datatype. Unlike numpy arrays however, Tensors are immputable; i.e. you can't update the contents of a tensor.

Tensors are described by their:

- __Shape__: Length of each of the axes
- __Rank__: Number of axes
- __Size__: Total number of elements in the tensor.

Lets instantiate some basic Tensors

In [4]:
# Create a tensor

x = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)
print("dtype:", x.dtype)
print("shape:", x.shape)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
dtype: <dtype: 'int32'>
shape: (3, 3)


In [5]:
# We can also specify the dtype

x = tf.constant([[1,2,3],[4,5,6],[7,8,9]], dtype=tf.float64)
print(x.dtype)

<dtype: 'float64'>


In [6]:
# Some other common methods of instantiating tensors:

# Constants
zeros = tf.zeros(shape=(1,6))
ones = tf.ones(shape=(2,3))
eights = tf.constant(8, shape=(3,4))

print("\n Zeros:\n ", zeros)
print("\n Ones:\n ", ones)
print("\n Eights: ", eights)


# Randomly sampled
normal = tf.random.normal(shape=(2,2), mean=0, stddev=1.)
uniform = tf.random.uniform(shape=(2,1), minval=0, maxval=10, dtype='int32')
poisson = tf.random.poisson((2,2), 5)


print("\n\n normal:\n ", normal)
print("\n uniform:\n ", uniform)
print("\n poisson: ", poisson)


 Zeros:
  tf.Tensor([[0. 0. 0. 0. 0. 0.]], shape=(1, 6), dtype=float32)

 Ones:
  tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)

 Eights:  tf.Tensor(
[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]], shape=(3, 4), dtype=int32)


 normal:
  tf.Tensor(
[[ 0.10802658 -1.4983894 ]
 [ 0.3651539   0.7563148 ]], shape=(2, 2), dtype=float32)

 uniform:
  tf.Tensor(
[[9]
 [7]], shape=(2, 1), dtype=int32)

 poisson:  tf.Tensor(
[[3. 0.]
 [7. 4.]], shape=(2, 2), dtype=float32)


In [7]:
# Tensors of different ranks

# Scalar
rank_0_tensor = tf.constant(6) 
# Vector
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
# Matrix
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)

# Generalizable to arbitrary number of axes
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])


# Print the rank, shape and size of tensors
print( 'Rank of rank_2_tensor : ', tf.rank(rank_2_tensor) )
print( 'Rank of rank_3_tensor : ', tf.rank(rank_3_tensor) )
print()
print( 'Rank of rank_2_tensor : ', rank_2_tensor.shape )
print( 'Rank of rank_3_tensor : ', rank_3_tensor.shape )
print()
print( 'Rank of rank_2_tensor : ', tf.size(rank_2_tensor) )
print( 'Rank of rank_3_tensor : ', tf.size(rank_3_tensor) )

Rank of rank_2_tensor :  tf.Tensor(2, shape=(), dtype=int32)
Rank of rank_3_tensor :  tf.Tensor(3, shape=(), dtype=int32)

Rank of rank_2_tensor :  (3, 2)
Rank of rank_3_tensor :  (3, 2, 5)

Rank of rank_2_tensor :  tf.Tensor(6, shape=(), dtype=int32)
Rank of rank_3_tensor :  tf.Tensor(30, shape=(), dtype=int32)


#### a) A few basic math operations

In [9]:
a = tf.constant([[1.0, 2.0], 
                 [3.0, 4.0]])
b = tf.constant([[1.0, 1.0], 
                 [0.0, 1.0]])


print(tf.add(a, b), "\n")
print(tf.subtract(a,b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2. 3.]
 [3. 5.]], shape=(2, 2), dtype=float32) 

tf.Tensor(
[[0. 1.]
 [3. 3.]], shape=(2, 2), dtype=float32) 

tf.Tensor(
[[1. 2.]
 [0. 4.]], shape=(2, 2), dtype=float32) 

tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32) 



In [10]:
# Equivalently
print(a + b, "\n") # element-wise addition
print(a - b, "\n") # element-wise subtraction
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2. 3.]
 [3. 5.]], shape=(2, 2), dtype=float32) 

tf.Tensor(
[[0. 1.]
 [3. 3.]], shape=(2, 2), dtype=float32) 

tf.Tensor(
[[1. 2.]
 [0. 4.]], shape=(2, 2), dtype=float32) 

tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32) 



In [11]:
# Taking the absolute value
abs_a = tf.abs(a)

# Raising to a power
pow_ba = tf.pow(a,b)

print("\n ", abs_a)
print("\n ", pow_ba)


  tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

  tf.Tensor(
[[1. 2.]
 [1. 4.]], shape=(2, 2), dtype=float32)


#### b) Indexing, Slicing and Reshaping

The indexing, slicing and reshaping rules are similar to NumPy.

- index starts at 0
- colons `:` are used for slices `start:stop:step`

In [12]:
t1 = tf.constant([0, 1, 2, 3, 4, 5, 6, 7])



print(t1[1:4])

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [13]:
# Alternatively

print(tf.slice(t1,
               begin=[1],
               size=[3]))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [14]:
# Reshaping

x = tf.constant([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

shape1 = [8,2]
shape2 = [4,4]
shape3 = [2,2,2,2]


# Create Tensors of different shape

a = tf.constant(x, shape=shape1)
print("\n a:\n ", a)

b = tf.constant(x, shape=shape2)
print("\n b:\n ", b)

c = tf.constant(x, shape=shape3)
print("\n c:\n ", c)


 a:
  tf.Tensor(
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]], shape=(8, 2), dtype=int32)

 b:
  tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]], shape=(4, 4), dtype=int32)

 c:
  tf.Tensor(
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]], shape=(2, 2, 2, 2), dtype=int32)


In [15]:
# Expanding rank of Tensors

t1 = tf.expand_dims(c, 0)
t2 = tf.expand_dims(c, 1)
t3 = tf.expand_dims(c, 3)

print("\n After expanding dims:\n t1 shape: ", t1.shape, "\n t2 shape: ", t2.shape, "\n t3 shape: ", t3.shape)


# Squeezing redundant dimensions

t1 = tf.squeeze(t1, 0)
t2 = tf.squeeze(t2, 1)
t3 = tf.squeeze(t3, 3)

print("\n After squeezing:\n t1 shape: ", t1.shape, "\n t2 shape: ", t2.shape, "\n t3 shape: ", t3.shape)


 After expanding dims:
 t1 shape:  (1, 2, 2, 2, 2) 
 t2 shape:  (2, 1, 2, 2, 2) 
 t3 shape:  (2, 2, 2, 1, 2)

 After squeezing:
 t1 shape:  (2, 2, 2, 2) 
 t2 shape:  (2, 2, 2, 2) 
 t3 shape:  (2, 2, 2, 2)


#### c) Converting between Numpy Arrays and Tensorflow Tensors 

In [16]:
# Numpy array to tensor

Array = np.arange(12)
print('Numpy array: ', Array)


Tensor = tf.constant(Array, dtype=tf.float32)
print('Tensor: ', Tensor)

Numpy array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Tensor:  tf.Tensor([ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.], shape=(12,), dtype=float32)


In [17]:
# Tensor to Numpy array 

Tensor.numpy()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)

# 2. Variables 

Recall that Tensors are immutabele. Hence the following will throw an error:

```
x = tf.constant([[1,1],
                 [1,1]], dtype=tf.int32)
x[1,1] = 0
---------------------------------------------------------------------------
TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

```

However, training a model means updating its parameters, which are a set of tensors. This is where `tf.Variable` comes in. A variable is a tensor whose value be changed.

In [53]:
# To create a variable, we need to provide an initial value

my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
my_variable = tf.Variable(initial_value=tensor)

print("Shape: ", my_variable.shape)
print("DType: ", my_variable.dtype)
print("As NumPy: ", my_variable.numpy())

Shape:  (2, 2)
DType:  <dtype: 'float32'>
As NumPy:  [[1. 2.]
 [3. 4.]]


In [54]:
# The state of a variable can be modified via its assign method

my_variable.assign(tf.zeros((2,2)))

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [55]:
# We can also re-assign a subset of the coefficients

my_variable[:, 1].assign([1,1])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[0., 1.],
       [0., 1.]], dtype=float32)>

In [56]:
# We can also assign_add and assign_sub

print( my_variable.assign_add( tf.constant([[1.,1.],[1.,1.]]) ))
print( my_variable.assign_sub( tf.constant([[1.,1.],[1.,1.]]) ))

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [1., 2.]], dtype=float32)>
<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[0., 1.],
       [0., 1.]], dtype=float32)>


In [57]:
# Math ops will return a Tensor. Most Tensor ops will also apply to Variables.

a = tf.Variable([[1.0, 2.0], 
                 [3.0, 4.0]])
b = tf.Variable(tf.ones(shape=(2,2), dtype=tf.float32))

# Element wise addition
print( a + b )

# Matrix multiplication
print( a @ b )

tf.Tensor(
[[2. 3.]
 [4. 5.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[3. 3.]
 [7. 7.]], shape=(2, 2), dtype=float32)


In [58]:
#  Except Variables cannot be reshaped

a.assign( tf.ones(shape=(3,2), dtype=tf.float32) )

ValueError: Cannot assign to variable Variable:0 due to variable shape (2, 2) and value shape (3, 2) are incompatible

In [63]:
# We can also name our variables

x = tf.Variable(["Hello world!"], tf.string, name='string_var')
y  = tf.Variable([3.14159, 2.71828], tf.float64, name='float_var')

print(x.name)
print(y.name)

# By default, variables in models will acquire unique names automatically.

string_var:0
float_var:0


# 3. Automatic Differentiation 